using SwissForge.Core.Json;

namespace SwissForge.Core.Api
{
    /// <summary>
    /// Hand-built OpenAPI 3.0 description of the SwissForge API.
    /// <para>
    /// Written out rather than generated by reflection so it stays readable and so the
    /// descriptions can say useful things. It is served at <c>/openapi.json</c>, which means
    /// any client generator, Postman, or scripting agent can discover the whole surface
    /// without documentation drifting out of date in a separate file.
    /// </para>
    /// </summary>
    public static class OpenApi
    {
        public static JsonValue Document(string version)
        {
            var doc = JsonValue.Obj();
            doc.Set("openapi", "3.0.3");

            var info = JsonValue.Obj();
            info.Set("title", "SwissForge API");
            info.Set("version", version);
            info.Set("description",
                "Swiss-type CNC engine services: cutting data, multi-channel cycle time, job planning, " +
                "quoting, and NC program analysis. Endpoints under /api/v1/esprit/ read or write the " +
                "live ESPRIT document and are only available when SwissForge is hosted inside ESPRIT; " +
                "everything else works standalone.");
            doc["info"] = info;

            var server = JsonValue.Obj();
            server.Set("url", "http://127.0.0.1:8731");
            server.Set("description", "SwissForge, hosted on loopback by the ESPRIT add-in or the CLI.");
            doc["servers"] = JsonValue.Arr().Add(server);

            // --- security
            var bearer = JsonValue.Obj();
            bearer.Set("type", "http");
            bearer.Set("scheme", "bearer");
            bearer.Set("description", "Token printed by the add-in on startup, or set in swissforge.config.json.");
            var schemes = JsonValue.Obj();
            schemes["bearerAuth"] = bearer;
            var components = JsonValue.Obj();
            components["securitySchemes"] = schemes;
            doc["components"] = components;
            doc["security"] = JsonValue.Arr().Add(JsonValue.Obj().Set("bearerAuth", JsonValue.Arr()));

            var paths = JsonValue.Obj();

            paths["/health"] = Path("get", "Liveness probe", "health",
                "Returns 200 whenever the server is up. The only endpoint that does not require a token.");

            paths["/openapi.json"] = Path("get", "This document", "meta", "");

            paths["/api/v1/status"] = Path("get", "Service and ESPRIT connection status", "status",
                "Tells you whether the engines are available and whether a live ESPRIT document is attached.");

            paths["/api/v1/materials"] = Path("get", "List materials", "reference",
                "The loaded material library, with a costIsIndicative flag marking any price that is " +
                "still a built-in placeholder rather than your purchase price. Optional ?group= filter.");

            paths["/api/v1/materials/{id}"] = Path("get", "One material by id or name", "reference",
                "Accepts an exact id or a fuzzy name, so both '303' and 'SS303' resolve.");

            paths["/api/v1/tools"] = Path("get", "List the loaded tool library", "reference", "");
            paths["/api/v1/machine"] = Path("get", "The configured machine profile", "reference", "");

            paths["/api/v1/feeds-speeds"] = Path("post", "Recommend cutting data", "engine",
                "Body: material (id), tool (id or full object), operation, workDiameterMm, and optionally " +
                "radialStockMm, cutLengthMm, targetRaMicron, toleranceMm, unsupportedLengthMm, threadPitchMm, " +
                "guideBushingEngaged. Returns speed, feed, depth of cut, pass count, predicted finish, " +
                "spindle power, and an advisories array explaining every clamp and derate applied.");

            paths["/api/v1/cycle-time"] = Path("post", "Schedule operations across channels", "engine",
                "Body: operations[] and optionally machine. Honours waitcodes and exclusive operations, " +
                "and returns the real cycle time, the per-channel idle time, the bottleneck channel, and " +
                "any deadlocked or orphaned waitcodes.");

            paths["/api/v1/plan"] = Path("post", "Plan a job from a part specification", "engine",
                "Body: part, and optionally machine, tools, template. Returns a full multi-channel " +
                "operation list with cutting data, a timed schedule, and advisories for anything assumed.");

            paths["/api/v1/quote"] = Path("post", "Price a part", "engine",
                "Body: part, and optionally machine, policy, tools, cycleSeconds, quantityBreaks. " +
                "If cycleSeconds is omitted the job is planned first to derive one. Returns a full cost " +
                "breakdown and a quantity-break table. isQuotable is false when something makes the " +
                "number untrustworthy, and the reason is in the advisories.");

            paths["/api/v1/gcode/lint"] = Path("post", "Static analysis of an NC program", "gcode",
                "Body: gcode (the NC text), and optionally machine, dialect, name. Catches unclamped G96, " +
                "feed moves with no F, cuts with no spindle, unpaired and mismatched waitcodes, arcs with " +
                "no geometry, mixed units, and more. Each finding carries a line number and a suggested fix.");

            paths["/api/v1/gcode/analyze"] = Path("post", "Structural analysis of an NC program", "gcode",
                "Body: gcode, optionally dialect and includeBlocks. Returns the channel split, a waitcode " +
                "pairing table, and per-channel statistics.");

            paths["/api/v1/esprit/probe"] = Path("get", "Report what this ESPRIT build exposes", "esprit",
                "Interrogates the live object model. Run this once after installation and send the output " +
                "back if an adapter member needs correcting for your version.");

            paths["/api/v1/esprit/stock"] = Path("get", "Stock definition from the active document", "esprit", "");
            paths["/api/v1/esprit/tools"] = Path("get", "Tool list from the active document", "esprit", "");
            paths["/api/v1/esprit/operations"] = Path("get", "Operation list from the active document", "esprit", "");

            paths["/api/v1/esprit/cutting-data"] = Path("post", "Push cutting data into ESPRIT", "esprit",
                "Body: updates[] of { operationId, speedRpm?, feedMmPerRev?, depthOfCutMm?, reason? }. " +
                "Returns how many applied and how many were skipped.");

            paths["/api/v1/esprit/post"] = Path("post", "Run a post processor and lint the result", "esprit",
                "Body: postProcessor, optionally lint (default true). Returns the NC text and, unless " +
                "suppressed, a lint report on it.");

            doc["paths"] = paths;
            return doc;
        }

        private static JsonValue Path(string method, string summary, string tag, string description)
        {
            var op = JsonValue.Obj();
            op.Set("summary", summary);
            if (!string.IsNullOrEmpty(description)) op.Set("description", description);
            op["tags"] = JsonValue.Arr().Add(JsonValue.Str(tag));

            var ok = JsonValue.Obj();
            ok.Set("description", "Success");
            var responses = JsonValue.Obj();
            responses["200"] = ok;

            var err = JsonValue.Obj();
            err.Set("description", "Error. Body is { error, message, status }.");
            responses["default"] = err;
            op["responses"] = responses;

            var path = JsonValue.Obj();
            path[method] = op;
            return path;
        }
    }
}
